[[language]]
name = "typescript"
formatter = { command = "yarn", args = ["prettier", "--stdin", "-w"] }

[language-server.ruby-lsp]
command = "ruby-lsp"
config = { diagnostics = true, formatting = true }

[language-server.steep]
command = "steep"
args = ["langserver"]

[[language]]
name = "ruby"
language-servers = ["ruby-lsp", "steep"]
auto-format = true
